name: cafe_menu_temp
description: "Cafe menu"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  appwrite: ^14.0.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.10
  cupertino_icons: ^1.0.8
  octo_image: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iran_sans.ttf
        - asset: assets/fonts/iran_sans_ultra_light.ttf
          weight: 100
        - asset: assets/fonts/iran_sans_light.ttf
          weight: 300
        - asset: assets/fonts/iran_sans_medium.ttf
          weight: 500
        - asset: assets/fonts/iran_sans_bold.ttf
          weight: 900

    - family: IranSansFaNum
      fonts:
        - asset: assets/fonts/iran_sans.ttf
        - asset: assets/fonts/iran_sans_fa_num_ultra_light.ttf
          weight: 100
        - asset: assets/fonts/iran_sans_fa_num_light.ttf
          weight: 300
        - asset: assets/fonts/iran_sans_fa_num_medium.ttf
          weight: 500
        - asset: assets/fonts/iran_sans_fa_num_bold.ttf
          weight: 900

